import Hero from '@/components/Hero'
import Menu from '@/components/Menu'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react';


let value
if (typeof window !== 'undefined') {
  value = JSON.parse(window.localStorage.getItem('cartData'))
}

export default function Home() {
  const [cart, setCart] = useState([])


  useEffect(() => {
    if(value != null ) setCart(value)
  },[])

  useEffect(() => {
    window.localStorage.setItem("cartData", JSON.stringify(cart));
  },[cart])

  const addToCart = (product) => {
    setCart([...cart, product])
  }

  const removeFromCart = (productToRemove) => {
    setCart(
      cart.filter((product) => product != productToRemove)
    )
  }

  

  
  console.log(cart.length)
  return (
    <>
      <Head>
        <title>Smart Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero cart={cart} quantity={cart.length} removeFromCart={removeFromCart}/>
      <Menu addToCart={addToCart}/>
    </>
  )
}
